metric:
  goal: maximize
  name: Attack Success rate (%)
method: grid
project: "baseline hackattend 2.0"
parameters:
  # layer_mask_type:
  #   values: ["111111111111","000000000001", "100000000000","000001000000"
  #   # "000000000010","000000000100","000000001000","000000010000","000000100000","000001000000","000010000000","000100000000","001000000000","010000000000","100000000000",
  #   ]
  top_percentage_in_layer:
    values: [0.01]
  aadv:
    values: [1]
  # attn_head_mask:
  #   values: ["111111111111"]
  # attn_layer_mask:
  #   values: ["111111111111"]
  task_name:
    values: ["dream", "reclor", "hellaswag","sst-2"]
    # values: ["dream"]
    # values: ["sst-2"]
  attack_strat:
    values: ["greedy"]
  head_tuple_size:
    values: ["12,12"]
  layer_tuple_size:
    values: ["12,12"]
  random_strat:
    values: ["random_random", "random_gair","importance_random"]
    # values: []
  seed:
    values: [72, 73, 74]
command:
  - python
  - "run_hackattend.py"
  - "--best_epoch"
  - "best"
  - "--do_lower_case"
  - "--max_combinations"
  - "3"
  - ${args}
